In [2]:
import cv2
import numpy as np

img = cv2.imread('car1.jpeg', cv2.IMREAD_GRAYSCALE)
print(img)

n_white_pix = np.sum(img == 255)
print('Number of white pixels:', n_white_pix)

[[126 105  93 ...  55  58  51]
 [ 99  88  85 ...  58  70  72]
 [ 93  95 111 ...  49  57  58]
 ...
 [161 162 162 ... 165 166 166]
 [158 158 159 ... 172 173 174]
 [160 161 158 ... 171 173 170]]
Number of white pixels: 1047
